_ fixed a bug when using the script without parameter
git-svn-id: svn+ssh://gforge/svn/siconos/trunk@51 bf01a9d7-0df3-0310-8ad4-b1c94d9ae2d5

diff --git a/Kernel/siconos/siconos.in b/Kernel/siconos/siconos.in
--- a/Kernel/siconos/siconos.in
+++ b/Kernel/siconos/siconos.in
@@ -83,21 +83,22 @@ if "$clean" = "true"; then
 fi;
 
 
-sample="false"
+sample="false";
 # test if there are one argument. if not, exit
 if [ $# -gt 1 ]; then
     echo "$0 : Bad number of argument";
-    sample="true";
     exit 1;
 fi;
 	
 # test if command file exist. if not, exit
-if [ ! -f $1 ]; then
-    echo "$1 file not found.";
-    sample="false"
-    exit 1;
-else
-    sample="true"
+if [ $# -eq 1 ]; then
+    if [ ! -f $1 ]; then
+	echo "$1 file not found.";
+	sample="false"
+	exit 1;
+    else
+	sample="true"
+    fi;
 fi;
     
 
